feat: only support webpack5 and html-webpack-plugin5
vuejs/preload-webpack-plugin pull request #14
Opened 2021-01-07 07:30 UTC by githoniel

RT

Note: It does not support old version of  webpack4 and html-webpack-plugin. But if it's need, I could and support for webpack4

2021-01-07 07:31 UTC, githoniel commented
@sodatea I think @vue/cli@5.0.0 may need this

2021-01-28 04:42 UTC, skyrex-mark commented
any updates on this pr?

2021-02-09 12:42 UTC, sodatea requested changes
Thank you so much for the help!

A few things, though:
1. `yarn.lock` contains private registry URLs, please fix
2. It would be better if webpack 4 can still be supported. (It's okay to drop support if that's not easy)

2021-02-10 06:39 UTC, githoniel commented
> Thank you so much for the help!
> 
> A few things, though:
> 
> 1. `yarn.lock` contains private registry URLs, please fix
> 2. It would be better if webpack 4 can still be supported. (It's okay to drop support if that's not easy)

ok i will fix both

2021-02-10 13:49 UTC, sodatea commented on package.json
> +    "html-webpack-plugin": ">=5.0.0 || ^^4.5.1",
```suggestion
    "html-webpack-plugin": ">=5.0.0 || ^4.5.1",
```

2021-02-12 03:02 UTC, sodatea approved these changes
Looks good to me. Thanks!

2021-02-12 03:02 UTC, merged

2021-02-12 03:03 UTC, skyrex-mark commented
Thank you for all the hard work on adding w5 support!

2021-02-12 19:58 UTC, skyrex-mark commented
It seems like there is no release for this change yet. Is there a plan to release this to npm soon? @sodatea

2021-02-13 01:27 UTC, sodatea commented
It's Lunar New Year holiday here… I'll release the new version when I have the time.

2021-02-13 11:16 UTC, sodatea commented
@skyrex-mark Released as v2.0.0